export enum ErrorType {
    SERVER_NOT_RESPONDING = 'SERVER_NOT_RESPONDING',
    ERROR_CAR_BUY = 'ERROR_CAR_BUY',
    ERROR_CAR_UPDATE = 'ERROR_CAR_UPDATE',
    ERROR_RACE = 'ERROR_RACE',
    ERROR_WEEK_TASK = 'ERROR_WEEK_TASK',
    ERROR_CLAIM = 'ERROR_CLAIM',
}